CREATE TABLE IF NOT EXISTS student_qr_code (
    qrID INT AUTO_INCREMENT PRIMARY KEY,
    studentID VARCHAR(30) NOT NULL UNIQUE,
    qr_token VARCHAR(100) NOT NULL UNIQUE,
    qr_content VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
